version: '3.5'
services:
  openvpn:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: openvpn
    restart: always
    cap_add:
      - NET_ADMIN      
    ports:
      - 1194:1194/udp
    networks:
      docker:
    logging:
      options:
        max-size: 100M

networks:
  docker: